 

  export const TOPNavbar = [
    {
      "id": 1,
      "time": "Today, 3:30 PM",
      "city": "•  Manchester",
      "match": "• 2nd TEST",
      "country1st": "England",
      "country2nd": "South Africa",
      "status": "Match yet to begin",
      "b2": "Fantasy",
      "b3": "Videos",
      "team1-score": "",
      "team2-s": "",
      "team2-score": "",
      "result": ""
    },
    {
      "id": 2,
      "time": "RESULT",
      "city": "•  Lord's",
      "match": "• Men's Hundred",
      "country1st": "LS-M",
      "country2nd": "WF-M",
      "status": "•  T20",
      "b2": "Table",
      "b3": "Report",
      "team1-score": "156/6",
      "team2-s": "(100 balls, T:157)",
      "team2-score": "139/9",
      "result": "Spirit won by 17 runs"
    },
    {
      "id": 3,
      "time": "RESULT",
      "city": "•  Basseterre",
      "match": "• 6IXTY (W)",
      "country1st": "GAW-W",
      "country2nd": "TKR-W",
      "status": "Amazon WMN won by 15 runs",
      "b2": "Table",
      "b3": "",
      "team1-score": "81/2",
      "team2-s": "(9.3/10 ov, T:82)",
      "team2-score": "66",
      "result": ""
    },
    {
      "id": 4,
      "time": "RESULT",
      "city": "•  Al Amerat",
      "match": "• Asia Cup QLF",
      "country1st": "HKG",
      "country2nd": "UAE",
      "status": "Hong Kong won by 8 wickets (with 6 balls remaining)",
      "b2": "Table",
      "b3": "",
      "team1-score": "149/2",
      "team2-s": "(19/20 ov, T:148)",
      "team2-score": "147",
      "result": "•  T20I"
    },
    {
      "id": 5,
      "time": "RESULT",
      "city": "•  Lord's",
      "match": "• Women's Hundred",
      "country1st": "LS-W",
      "country2nd": "WF-W",
      "status": "Spirit won by 8 wickets (with 14 balls remaining)",
      "b2": "Table",
      "b3": "Report",
      "team1-score": "122/2",
      "team2-s": "(86/100 balls, T:120)",
      "team2-score": "119/9",
      "result": ""
    },
    {
      "id": 6,
      "time": "RESULT",
      "city": "•  Basseterre",
      "match": "• 6IXTY (W)",
      "country1st": "GAW-W",
      "country2nd": "BR-W",
      "status": "Amazon WMN won by 5 wickets (with 12 balls remaining)",
      "b2": "Table",
      "b3": "",
      "team1-score": "59/1",
      "team2-s": "(8/10 ov, T:59)",
      "team2-score": "58",
      "result": ""
    },
    {
      "id": 7,
      "time": "RESULT",
      "city": "•  Al Amerat",
      "match": "• Asia Cup QLF",
      "country1st": "KUW",
      "country2nd": "SGP",
      "status": "Kuwait won by 6 wickets (with 73 balls remaining)",
      "b2": "Table",
      "b3": "",
      "team1-score": "105/4",
      "team2-s": "(7.5/20 ov, T:105)",
      "team2-score": "104",
      "result": "•  T20I"
    },
    {
      "id": 8,
      "time": "RESULT",
      "city": "•  Amstelveen",
      "match": "• 2nd ODI",
      "country1st": "IRE-W",
      "country2nd": "NL-W",
      "status": "Ire Women won by 210 runs",
      "b2": "",
      "b3": "",
      "team1-score": "337/8",
      "team2-s": "(33.2/50 ov, T:338)",
      "team2-score": "127",
      "result": ""
    },
    {
      "id": 9,
      "time": "RESULT",
      "city": "•  Basseterre",
      "match": "• 6IXTY (W)",
      "country1st": "BR-W",
      "country2nd": "TKR-W",
      "status": "Royals WMN won by 28 runs",
      "b2": "Table",
      "b3": "",
      "team1-score": "108/4",
      "team2-s": "(10 ov, T:109)",
      "team2-score": "80/3",
      "result": ""
    },
    {
      "id": 10,
      "time": "Today, 7:00 PM",
      "city": "•  Bengaluru",
      "match": "• Maharaja T20",
      "country1st": "Gulbarga Mystics",
      "country2nd": "Mysuru Warriors",
      "status": "Match yet to begin",
      "b2": "Table",
      "b3": "Fantasy",
      "team1-score": "",
      "team2-s": "",
      "team2-score": "",
      "result": ""
    },
    {
      "id": 11,
      "time": "Today, 8:00 PM",
      "city": "•  Southampton",
      "match": "• Women's Hundred",
      "country1st": "Southern Brave (Women)",
      "country2nd": "Trent Rockets (Women)",
      "status": "Match yet to begin",
      "b2": "Table",
      "b3": "Fantasy",
      "team1-score": "",
      "team2-s": "",
      "team2-score": "",
      "result": ""
    },
    {
      "id": 12,
      "time": "Today, 7:30 PM",
      "city": "•  Basseterre",
      "match": "• 6IXTY (M)",
      "country1st": "Guyana Amazon Warriors",
      "country2nd": "St Lucia Kings",
      "status": "Match yet to begin",
      "b2": "Table",
      "b3": "Fantasy",
      "team1-score": "",
      "team2-s": "",
      "team2-score": "",
      "result": ""
    },
    {
      "id": 13,
      "time": "Today, 10:00 PM",
      "city": "•  Basseterre",
      "match": "• 6IXTY (M)",
      "country1st": "St Kitts and Nevis Patriots",
      "country2nd": "Jamaica Tallawahs",
      "status": "Match yet to begin",
      "b2": "Table",
      "b3": "Fantasy",
      "team1-score": "",
      "team2-s": "",
      "team2-score": "",
      "result": ""
    },
    {
      "id": 14,
      "time": "Today, 11:30 PM",
      "city": "•  Southampton",
      "match": "• Men's Hundred",
      "country1st": "Southern Brave (Men)",
      "country2nd": "Trent Rockets (Men)",
      "status": "Match yet to begin",
      "b2": "Table",
      "b3": "Fantasy",
      "team1-score": "",
      "team2-s": "",
      "team2-score": "",
      "result": "•  T20"
    },
    {
      "id": 15,
      "time": "Tomorrow, 12:30 AM",
      "city": "•  Basseterre",
      "match": "• 6IXTY (W)",
      "country1st": "Barbados Royals Women",
      "country2nd": "Trinbago Knight Riders Women",
      "status": "Match yet to begin",
      "b2": "Table",
      "b3": "Fantasy",
      "team1-score": "",
      "team2-s": "",
      "team2-score": "",
      "result": ""
    },
    {
      "id": 16,
      "time": "Tomorrow, 3:00 AM",
      "city": "•  Basseterre",
      "match": "• 6IXTY (M)",
      "country1st": "Barbados Royals",
      "country2nd": "Trinbago Knight Riders",
      "status": "Match yet to begin",
      "b2": "Table",
      "b3": "Fantasy",
      "team1-score": "",
      "team2-s": "",
      "team2-score": "",
      "result": ""
    }
   ];
 